### ISSUE TITLE
One resource in command.sh can not be opened

### ISSUE THREAD

**Issue by jerrywu65** [ml-jku/lsc#1]
This is the url:
https://sourceforge.net/code-snapshots/svn/j/jc/jcompoundmapper/code/jcompoundmapper-code-r55.zip

**Comment by AndreasMayr** [comment]
Thank you for bringing this up. I think the URL has to be accessed before by the web browser. But I hope, that I found a solution, that works independent of that:
svn export svn://svn.code.sf.net/p/jcompoundmapper/code/ $HOME/myprogs/jcompoundmapper-code-r55 -r 55
(already updated in commdands.sh)

**Comment by jerrywu65** [comment]
I am very sorry for bothering you , but could you tell me how long did it take you to run the entire program?Thank You.

**Comment by AndreasMayr** [comment]
It's difficult to say, what the overall runtime was. But for the Deep Learning code (fully connected networks) a rough estimation is 0.3 to 1.3 days per network (depending on the network parameters, the current data size, and the used GPU). However I had more processes in parallel on a GPU and had additionally multiple GPUs and multiple servers with GPUs (in order to get all results). The graph-convolution architecture and the LSTM architecture, I used, took significantly longer, as far as I remember.
For the C++ code: Especially SVMs took quite long (maybe as a rough estimate 1-2 months), but it was computed on an older server (with slower CPUs, but with much main memory (~2 TB)).
