### ISSUE TITLE
Help！

### ISSUE THREAD

**Issue by jiangshunyu** [ml-jku/lsc#3]
I am very sorry for bothering you , but could tell me how you matched each compound to its target?
What I understand is that 450,000 compounds, each compound corresponds to multiple assays, there are 1310 assays in total, but these assays are not enough to describe the properties of the compound, so some assays will correspond to some targets, and what I want to know is how do you directly match the compound to the target?

**Comment by AndreasMayr** [comment]
Assays are assigned to targets (e.g. what protein, etc. does the assay measure?). So, if you want it like that: Assays measure compound activities, and since you know to which target an assay corresponds, you potentially have an idea about the target activity of a compound.
But consider in this case e.g.: assays measuring antagonists, and assays measuring agonists cannot be compared, since an antagonist is negative in an agonist assay and vice versa ==> merging different assays to a target might be a problem (even if the same target is assigned to different assays)

All this information is extracted from the ChEMBL database.

Scripts for extracting Assay-Compound relations:
https://github.com/ml-jku/lsc/blob/master/extractChEMBL.sql
https://github.com/ml-jku/lsc/blob/master/createTrainTable.R

Analysis Script relating assays an proteins over targets:
https://github.com/ml-jku/lsc/blob/master/analysis/chemblSelForAnalysis.sql

**Comment by jiangshunyu** [comment]
> Assays are assigned to targets (e.g. what protein, etc. does the assay measure?). So, if you want it like that: Assays measure compound activities, and since you know to which target an assay corresponds, you potentially have an idea about the target activity of a compound.
> But consider in this case e.g.: assays measuring antagonists, and assays measuring agonists cannot be compared, since an antagonist is negative in an agonist assay and vice versa ==> merging different assays to a target might be a problem (even if the same target is assigned to different assays)
> 
> All this information is extracted from the ChEMBL database.
> 
> Scripts for extracting Assay-Compound relations:
> https://github.com/ml-jku/lsc/blob/master/extractChEMBL.sql
> https://github.com/ml-jku/lsc/blob/master/createTrainTable.R
> 
> Analysis Script relating assays an proteins over targets:
> https://github.com/ml-jku/lsc/blob/master/analysis/chemblSelForAnalysis.sql

I am very honored to receive your reply.
 
Thank you very much for your advice. I will try it myself.
